### ISSUE TITLE
Error:  'basics' is not loaded. It was not found (try to install it).

### ISSUE THREAD

**Issue by parmentf** [touv/node-ezs#5]
I am unable to run any ezs script with a `[use]` command.

```bash
$ ezs ../node-ezs-istex/examples/categories.ezs
/home/parmentf/prog/node-ezs/lib/statement.js:68
                        throw new Error('\'' + name + '\' is not loaded. It was not found (try to install it).');
                        ^

Error: 'basics' is not loaded. It was not found (try to install it).
    at /home/parmentf/prog/node-ezs/lib/statement.js:68:31
    at Array.forEach (<anonymous>)
    at /home/parmentf/prog/node-ezs/lib/statement.js:41:23
    at Array.forEach (<anonymous>)
    at Object.get (/home/parmentf/prog/node-ezs/lib/statement.js:35:14)
    at Function.ezs.all (/home/parmentf/prog/node-ezs/lib/index.js:102:58)
    at ezs.command (/home/parmentf/prog/node-ezs/lib/index.js:149:32)
    at Array.reduce (<anonymous>)
    at new Pipeline (/home/parmentf/prog/node-ezs/lib/pipeline.js:44:29)
    at Function.ezs.pipeline (/home/parmentf/prog/node-ezs/lib/index.js:96:12)
```

even though the `ezs-basics` module is locally installed (and even globally).

```bash
$ npm ls --depth=0
/home/parmentf/prog/test-ezs
├── UNMET PEER DEPENDENCY ezs@^5.3.7
├── ezs-basics@3.6.4
└── ezs-istex@4.3.3

npm ERR! peer dep missing: ezs@^5.3.7, required by ezs-basics@3.6.4
npm ERR! peer dep missing: ezs@^4.6.2, required by ezs-istex@4.3.3
npm ERR! extraneous: core-js@2.5.7 /home/parmentf/prog/test-ezs/node_modules/babel-runtime/node_modules/core-js
npm ERR! extraneous: tunnel-agent@0.4.3 /home/parmentf/prog/test-ezs/node_modules/caw/node_modules/tunnel-agent
npm ERR! extraneous: minimist@0.0.8 /home/parmentf/prog/test-ezs/node_modules/mkdirp/node_modules/minimist
```

**Comment by parmentf** [comment]
Should be fixed by 0758632067efd
